### ISSUE TITLE
Install / config management?

### ISSUE THREAD

**Issue by jmandel** [OBHITA/Consent2Share#1]
Just wondering if there is a tutorial, readme, chef script, docker container, or some other info/resources describing how to get this stack up and running.

**Comment by jonbartels** [comment]
I'm going through similar getting started issues. @jmandel were you able to get this project up and running? Any notes to share? Thank you for checking back on a 2 year old comment!

So far this looks like a standard maven project and the output from mvn package will be a WAR. I'm getting a build going now and I assume that the WAR can be deployed to any Java app server.

**Comment by jmandel** [comment]
I don't fully recall, but I don't believe I pursued this. Code appears not to have been documented, updated, or maintained.

**Comment by tlin-fei** [comment]
@jmandel, @jmandel, these projects are standard Java/Spring maven projects. You first need "mvn clean install" these two projects under ThirdParty folder. Other projects depend on the artifacts from these two projects. You can  then build the projects by going to DS4P folder and run "mvn clean install".  OBHITA consent2share was ended in 2014. but Consent2Share among other projects are still in development under BHITS (https://github.com/BHITS). We do have installation guide for Consent2Share and we will do a better documentation on Github for source code released under BHITS.

**Comment by jonbartels** [comment]
@tlin-fei, you are correct that this is a fairly clear maven project.

There are a few gotchas I found as I worked through the build process today. My raw notes follow. 

Some of my notes are specific to my environment (eg maven version) or hacky (eg removing the logging exclusion). I think some of the dependencies may not be available from the given repositories. If my schedule permits I'll write up an INSTALL.md and send a pull request next week. 

I apologize for not providing more formal feedback but I was using some free time to experiment and did not plan for proper feedback to the project.

> mvn enforcer very picky about java, mvn, other versions. Altered it to >3, so my install of mvn 3.2.5 would work
> 
> run mvn install on common library for unit testing and common library projects
> 
> update org.herasaf.xacml.core version from 1.0.0 M3 to 1.0.1.RELEASE as only 1.0.1 is available in 
> repos
> 
> echosign dependencies
> in Third Party, run mvn install in ehcosign project
> 
> update repos to find one that hosts net.taldius:clamav
> - remove herasaf repo
> - add linpki repo which has the clamav library available
> - comment out enforcer for commons logging, clamav drags it in; this will probably impact logging; right way to fix it is to add an exclusion to the net.taldius dependency I think
> 
> now mvn package in the DS4P project works.
>
> tried to deploy consent2share WAR to Glassfish, got errors. Not sure if this is a build issue or glassfish issue
